name: Run Cargo Tests

on:
  pull_request:
    branches:
      - master 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@1
        with:
          rust-version: stable

      - name: Run tests
        run: cargo test --verbose

